name       : qelectrotech
version    : '0.70'
release    : 3
source     :
    - https://git.tuxfamily.org/qet/qet.git/snapshot/qet-0.7.0.tar.gz : d9d7de46c26f9ab9076d02463e9abd9b4b01e4e77202dc22ccecfe08d9bdd2c4
homepage   : https://qelectrotech.org/
license    : GPL-2.0-or-later
component  : office.scientific
summary    : QElectroTech is a Qt5 application to design electric diagrams.
description: |
    QElectrotech uses XML files for elements and diagrams, and includes both a diagram editor, a element editor, and an titleblock editor.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcoreaddons-devel
    - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-install-paths.patch
build      : |
    %qmake
install    : |
    %make_install INSTALL_ROOT=%installroot%
    rm -rf $installdir/usr/share/doc
