name       : qelectrotech
version    : 0.5
release    : 1
source     :
    - http://download.tuxfamily.org/qet/tags/20151127/qelectrotech-0.5-src.tar.gz : 361f0f0fd282bdbd1624f7590f6be24918f8be75266f2c09a07ad9453590ce67
license    : GPL-2.0
component  : office.scientific
summary    : QElectroTech is a Qt5 application to design electric diagrams.
description: |
    QElectrotech uses XML files for elements and diagrams, and includes both a diagram editor, a element editor, and an titleblock editor.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Network)
    - pkgconfig(Qt5PrintSupport)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5Xml)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-install-paths.patch
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=%installroot%
