name       : qelectrotech
version    : '0.91'
release    : 6
source     :
    - https://git.tuxfamily.org/qet/qet.git/snapshot/qet-0.9.1.tar.gz : adac0969f3046cf033b048e595f4d576e5e37d028b8bb51bfa7710a64a043634
homepage   : https://qelectrotech.org/
license    : GPL-2.0-or-later
component  : office.scientific
summary    : QElectroTech is a Qt5 application to design electric diagrams
description: |
    QElectrotech uses XML files for elements and diagrams, and includes both a diagram editor, a element editor, and an titleblock editor.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(sqlite3)
    - kcoreaddons-devel
    - kwidgetsaddons-devel
setup      : |
    patch -p1 < $pkgfiles/0001-Fix-install-paths.patch
build      : |
    %qmake
install    : |
    %make_install INSTALL_ROOT=%installroot%
    rm -rf $installdir/usr/share/doc
