name       : qelectrotech
version    : 0.61
release    : 2
source     :
    - https://download.tuxfamily.org/qet/tags/20180823/qelectrotech-0.61-src.tar.gz : ab1161a3c0f6d7c16c330daaf6cac67dcc0ce3aa5b2e8887a62aa91c99d6193b
license    : GPL-2.0-or-later
component  : office.scientific
summary    : QElectroTech is a Qt5 application to design electric diagrams.
description: |
    QElectrotech uses XML files for elements and diagrams, and includes both a diagram editor, a element editor, and an titleblock editor.
builddeps   :
    - pkgconfig(Qt5Svg)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-install-paths.patch

build      : |
    %qmake
install    : |
    %make_install INSTALL_ROOT=%installroot%
